# Generated by Django 4.2.5 on 2023-09-19 08:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("orginal_image_link", models.BooleanField(default=False)),
                ("time_limited_link", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="ThumbnailDimentions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("height", models.IntegerField()),
                ("width", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ImagexAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_type",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="account_type",
                        to="api_image.accounttier",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("add_time", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=128)),
                ("upload_image", models.ImageField(upload_to="images/")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api_image.imagexaccount",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExpiringLinks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("add_time", models.DateTimeField(auto_now_add=True)),
                (
                    "time_to_expire",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                300, message="Min sec value is 300"
                            ),
                            django.core.validators.MaxValueValidator(
                                30000, message="Max sec value is 30000"
                            ),
                        ]
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api_image.imagemodel",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owner",
                        to="api_image.imagexaccount",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="accounttier",
            name="image_size",
            field=models.ManyToManyField(to="api_image.thumbnaildimentions"),
        ),
    ]
