# Generated by Django 4.2.5 on 2023-09-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_image", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagemodel",
            name="upload_image",
            field=models.ImageField(upload_to=""),
        ),
    ]
