# Generated by Django 4.2.5 on 2023-09-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_image", "0002_alter_imagemodel_upload_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expiringlinks",
            name="image",
        ),
        migrations.AddField(
            model_name="expiringlinks",
            name="expiring_link",
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="expiringlinks",
            name="link_to_image",
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
