# Generated by Django 4.2.5 on 2023-09-20 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api_image", "0003_remove_expiringlinks_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expiringlinks",
            name="link_to_image",
        ),
        migrations.AddField(
            model_name="expiringlinks",
            name="image",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="api_image.imagemodel",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="expiringlinks",
            name="expiring_link",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
