# Generated by Django 4.2.5 on 2023-09-20 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api_image", "0004_remove_expiringlinks_link_to_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expiringlinks",
            name="image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orginal",
                to="api_image.imagemodel",
            ),
        ),
    ]
