# Generated by Django 4.2.5 on 2023-09-21 09:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api_image", "0006_rename_thumbnaildimentions_thumbnaildimensions_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ImagexAccount",
            new_name="ClientAccount",
        ),
    ]
