# Generated by Django 4.2.5 on 2023-09-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_image", "0008_alter_clientaccount_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedimage",
            name="upload_image",
            field=models.ImageField(upload_to="images"),
        ),
    ]
