# Generated by Django 4.2.5 on 2023-09-22 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api_image", "0010_remove_expiringlinks_owner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedimage",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_account",
                to="api_image.clientaccount",
            ),
        ),
    ]
