# Generated by Django 4.2.5 on 2023-09-22 11:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api_image", "0012_alter_expiringlinks_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="expiringlinks",
            old_name="image",
            new_name="image_id",
        ),
    ]
