# Generated by Django 4.2.5 on 2023-09-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_image", "0013_rename_image_expiringlinks_image_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expiringlinks",
            name="time_to_expire",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="thumbnaildimensions",
            name="height",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
